# Generated by Django 3.0 on 2020-04-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('addition_date', models.DateTimeField(verbose_name='Date added')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Series')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
