# Generated by Django 3.0 on 2020-04-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200413_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='series',
        ),
        migrations.RemoveField(
            model_name='film',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
